[project]
name = "project-pegasus"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.6.6",
    "httpx>=0.28.1",
    "langchain-cohere>=0.5.0",
    "langchain-mongodb>=0.9.0",
]
