store:
  provider: mongodb
  mongodb:
    database: "search"
    collection: "products"
    vector_index: "vector_index"
    search_index: "search_index"
  embeddings:
    provider: cohere
    model: "embed-english-v3.0"
llm:
  provider: cohere